import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/config/db';
import { ScreenConfigTable } from '@/config/schema';
import { openrouter } from '@/config/openrouter';
import { currentUser } from '@clerk/nextjs/server';
import { jsonrepair } from 'jsonrepair';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { projectId, prompt } = body;

    if (!projectId || !prompt) {
      return NextResponse.json({ error: 'Missing projectId or prompt' }, { status: 400 });
    }

    if (!process.env.OPENROUTER_API_KEY) {
      console.error('Missing OPENROUTER_API_KEY in add-screen route');
      return NextResponse.json({ error: 'OPENROUTER_API_KEY is not configured' }, { status: 500 });
    }

    const user = await currentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const response = await openrouter.chat.send({
      chatRequest: {
        model: 'openrouter/free',
        messages: [
          {
            role: 'user',
            content: `You are an expert UI/UX designer and React developer. Create a new screen configuration object that includes id, name, purpose, and layoutDescription for a new screen based on the user's prompt. Return only valid JSON and do not include markdown or extra commentary.\n\nUser prompt: ${prompt}`
          }
        ]
      }
    });

    let rawContent = response.choices?.[0]?.message?.content;
    if (!rawContent) {
      console.error('OpenRouter returned empty content for add-screen');
      return NextResponse.json({ error: 'Empty response from AI' }, { status: 500 });
    }

    const cleaned = String(rawContent).replace(/```json/g, '').replace(/```/g, '').trim();
    let parsed;
    try {
      const repairedJson = jsonrepair(cleaned);
      parsed = JSON.parse(repairedJson);
    } catch (error) {
      console.error('Add screen JSON parse error:', error, cleaned);
      return NextResponse.json({ error: 'Unable to parse AI response', raw: cleaned }, { status: 500 });
    }

    const newScreen = {
      projectId,
      screenId: parsed.id || `screen-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      screenName: parsed.name || 'New Screen',
      purpose: parsed.purpose || 'New screen generated by AI',
      screenDescription: parsed.layoutDescription || 'Generated layout description',
      code: ''
    };

    await db.insert(ScreenConfigTable).values(newScreen);
    return NextResponse.json({ screen: newScreen });
  } catch (error) {
    console.error('Add screen error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
